#@data/values-schema
---
env_flags: ""
msg_sizes: [12]
queue_type: classic
script: ""
script_name: client
clusters:
  - name: ""
    replicas: 1
    image: ""
    env_flags: ""
    config: ""
    advanced_config: ""
    kernel_config: ""
    queue_type: "cqv2"
    erl_args: ""
    env: ""
    mirroring: false
    plugins: [""]
lavinmq_clusters:
  - name: ""
    image: ""
    env_flags: ""
