#@data/values
---
#!
#! Deploys 3 identical envs per queue type / msg size
#! the goal is to see how much variance there is without
#! actual environment differences (image, config, etc)
#!
msg_sizes: [100, 5000]

clusters:
  - name: cq-env1
    replicas: 1
    image: pivotalrabbitmq/rabbitmq:main
    env_flags: -qa x-queue-version=2
  - name: cq-env2
    replicas: 1
    image: pivotalrabbitmq/rabbitmq:main
    env_flags: -qa x-queue-version=2
  - name: cq-env3
    replicas: 1
    image: pivotalrabbitmq/rabbitmq:main
    env_flags: -qa x-queue-version=2
  - name: qq-env1
    replicas: 1
    image: pivotalrabbitmq/rabbitmq:main
    env_flags: -qq
  - name: qq-env2
    replicas: 1
    image: pivotalrabbitmq/rabbitmq:main
    env_flags: -qq
  - name: qq-env3
    replicas: 1
    image: pivotalrabbitmq/rabbitmq:main
    env_flags: -qq
