#@ load("@ytt:data", "data")
#@ for msg_size in data.values.msg_sizes:
#@ for cluster in data.values.clusters:
#@ cluster_name = cluster.name + "-s" + str(msg_size)
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: #@ cluster_name
spec:
  replicas: #@ cluster.replicas
  image: #@ cluster.image
#@ if cluster.image.startswith("registry.pivotal.io"):
  imagePullSecrets:
    - name: pivotal
#@ end
  resources:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 2
      memory: 2Gi
  persistence:
    storageClassName: premium-rwo
    storage: "15Gi"
  rabbitmq:
    additionalPlugins: #@ ["rabbitmq_stream", "rabbitmq_stream_management"] + cluster.plugins
    #@yaml/text-templated-strings
    additionalConfig: |
      log.console.level = debug
      queue_master_locator = client-local
      queue_leader_locator = client-local
      cluster_formation.target_cluster_size_hint = (@= str(cluster.replicas) @)
      (@= cluster.config @)
    #@yaml/text-templated-strings
    advancedConfig: |
        [
        {rabbit, [
            {vm_memory_high_watermark,{relative,0.8}},
            {credit_flow_default_credit,{0,0}}
        ]},
        {prometheus, [
            {global_labels,[{<<"msg_size">>, (@= str(msg_size) @)}]}
        ]}
        ].
    #@yaml/text-templated-strings
    envConfig: |
      SERVER_ADDITIONAL_ERL_ARGS="+JPperf true (@= cluster.erl_args @)"
      (@= cluster.env @)
  #! service:
  #!   type: LoadBalancer
  override:
    statefulSet:
      spec:
        template:
          metadata:
            annotations:
              #! prevents pods from getting evicted
              cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          spec:
            containers:
            #! we often use mutable branch tags for images
              - name: rabbitmq
                imagePullPolicy: Always
                env:
                  - name: RABBITMQ_LOG
                    value: "debug"
#!                  - name: ERL_DIST_PORT
#!                    value: "25672"
            initContainers:
              - name: setup-container
                imagePullPolicy: Always

#@ end
#@ end
